language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t skarthik85/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skarthik85/react-test npm test -- --coverage

after_success:
  - docker build -t skarthik85/multi-client ./client
  - docker build -t skarthik85/multi-nginx ./nginx
  - docker build -t skarthik85/multi-server ./server
  - docker build -t skarthik85/multi-worker ./worker
  
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push skarthik85/multi-client
  - docker push skarthik85/multi-nginx
  - docker push skarthik85/multi-server
  - docker push skarthik85/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-781554925155'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
